name = "DeepTreeEchoSelf"
uuid = "a9c90001-0000-0000-0000-000000000001"
authors = ["o9c <o9nn@o9c.org>"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.9"
ModelingToolkit = "8.73"
DifferentialEquations = "7.10"
Symbolics = "5.10"
Graphs = "1.9"
PyCall = "1.96"
